"""Diagnostics viewer CLI for runtime telemetry snapshots.

Loads telemetry JSON exported by ``runtime_frame_telemetry.py`` and renders a
human-readable summary covering frame totals, streaming health, subsystem and
stage timings, scene validation issues, and metric samples filtered by prefix.

Usage (after exporting telemetry)::

    python scripts/diagnostics/telemetry_viewer.py \
        --input telemetry/frame_timings.json \
        --metric-prefix runtime.streaming.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Mapping, MutableMapping, Optional, Sequence

_METRIC_UNIT_SUFFIX = {
    "none": "",
    "count": "",
    "milliseconds": " ms",
    "seconds": " s",
    "bytes": " bytes",
    "percentage": " %",
}


@dataclass(frozen=True)
class MetricEntry:
    """Runtime metric sample resolved against its descriptor."""

    name: str
    unit: str
    description: str
    labels: Mapping[str, str]
    is_integral: bool
    value: float
    int_value: int

    def formatted_value(self) -> str:
        if self.is_integral:
            return str(self.int_value)
        return f"{self.value:.4f}"

    def formatted_unit(self) -> str:
        suffix = _METRIC_UNIT_SUFFIX.get(self.unit)
        if suffix is not None:
            return suffix
        return f" {self.unit}" if self.unit else ""

    def formatted_labels(self) -> str:
        if not self.labels:
            return ""
        parts = ", ".join(f"{key}={value}" for key, value in sorted(self.labels.items()))
        return f" [{parts}]"

    def formatted_description(self) -> str:
        if not self.description:
            return ""
        return f" — {self.description}" if self.description else ""


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a textual dashboard for runtime telemetry snapshots.",
    )
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Path to telemetry JSON generated by runtime_frame_telemetry.py.",
    )
    parser.add_argument(
        "--metric-prefix",
        action="append",
        default=[],
        help=(
            "Metric name prefix to display (repeatable). Defaults to runtime.streaming.*\n"
            "when unspecified."
        ),
    )
    parser.add_argument(
        "--max-issues",
        type=int,
        default=5,
        help="Maximum number of scene validation issues to display (default: 5).",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print extended annotations, including metric descriptions.",
    )
    return parser.parse_args(argv)


def _load_payload(path: Path) -> Mapping[str, object]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise SystemExit(f"error: telemetry file not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise SystemExit(f"error: failed to parse telemetry JSON: {exc}") from exc
    if not isinstance(data, Mapping):
        raise SystemExit("error: telemetry payload must be a JSON object")
    return data


def _resolve_metric_entries(
    descriptors: Sequence[Mapping[str, object]],
    samples: Sequence[Mapping[str, object]],
    prefixes: Optional[Sequence[str]],
) -> List[MetricEntry]:
    entries: List[MetricEntry] = []
    for sample in samples:
        index = int(sample.get("descriptor_index", -1))
        if index < 0 or index >= len(descriptors):
            continue
        descriptor = descriptors[index]
        name = str(descriptor.get("name", ""))
        if prefixes is not None and prefixes and not any(name.startswith(prefix) for prefix in prefixes):
            continue
        labels = descriptor.get("labels", {})
        if not isinstance(labels, Mapping):
            labels = {}
        description = str(descriptor.get("description", ""))
        unit = str(descriptor.get("unit", ""))
        entry = MetricEntry(
            name=name,
            unit=unit,
            description=description,
            labels={str(k): str(v) for k, v in labels.items()},
            is_integral=bool(sample.get("is_integral", False)),
            value=float(sample.get("value", 0.0)),
            int_value=int(sample.get("int_value", 0)),
        )
        entries.append(entry)
    entries.sort(key=lambda entry: (entry.name, tuple(sorted(entry.labels.items()))))
    return entries


def _format_section(title: str, lines: Iterable[str]) -> str:
    rendered = list(lines)
    if not rendered:
        return ""
    underline = "-" * len(title)
    body = "\n".join(rendered)
    return f"{title}\n{underline}\n{body}\n"


def _format_frame_summary(payload: Mapping[str, object]) -> str:
    frames = payload.get("frames", [])
    summary = payload.get("summary", {})
    if not isinstance(summary, Mapping):
        summary = {}
    lines = [f"Frames captured: {len(frames)}"]
    total_ms = summary.get("total_ms")
    if isinstance(total_ms, (int, float)):
        lines.append(f"Total frame time: {total_ms:.4f} ms")
    handoff_ms = summary.get("handoff_ms")
    if isinstance(handoff_ms, (int, float)):
        lines.append(f"Physics → geometry hand-off: {handoff_ms:.4f} ms")
    category_totals: MutableMapping[str, float] = {}
    for key, value in summary.items():
        if not isinstance(key, str) or not key.startswith("category:"):
            continue
        category = key.split(":", maxsplit=1)[1]
        if isinstance(value, (int, float)):
            category_totals[category] = float(value)
    if category_totals:
        lines.append("Category totals:")
        for category, duration in sorted(category_totals.items()):
            lines.append(f"  • {category}: {duration:.4f} ms")
    return _format_section("Frame Summary", lines)


def _format_streaming(diagnostics: Mapping[str, object]) -> str:
    streaming = diagnostics.get("streaming") if isinstance(diagnostics, Mapping) else None
    if not isinstance(streaming, Mapping):
        return ""
    keys = [
        "worker_count",
        "queue_capacity",
        "pending_tasks",
        "active_workers",
        "streaming_pending",
        "streaming_loading",
        "streaming_total_requests",
        "streaming_total_completed",
        "streaming_total_failed",
        "streaming_total_cancelled",
        "streaming_total_rejected",
    ]
    lines = [f"{key.replace('_', ' ').title()}: {int(streaming.get(key, 0))}" for key in keys]
    return _format_section("Streaming", lines)


def _format_initialization_failures(diagnostics: Mapping[str, object]) -> str:
    if not isinstance(diagnostics, Mapping):
        return ""

    def _coerce_int(value: object) -> int:
        if isinstance(value, bool):
            return int(value)
        if isinstance(value, (int, float)):
            return int(value)
        if isinstance(value, str):
            try:
                return int(value)
            except ValueError:
                return 0
        return 0

    total_failures = _coerce_int(diagnostics.get("initialize_failure_count"))
    has_last_failure = bool(diagnostics.get("has_initialize_failure"))
    last_failure = diagnostics.get("last_initialize_failure") if has_last_failure else None

    subsystem_summaries: List[str] = []
    subsystems = diagnostics.get("subsystems")
    if isinstance(subsystems, Sequence):
        for subsystem in subsystems:
            if not isinstance(subsystem, Mapping):
                continue
            count = _coerce_int(subsystem.get("initialize_failure_count"))
            if count <= 0:
                continue
            name = str(subsystem.get("name", "unknown")).strip() or "unknown"
            duration = subsystem.get("last_initialize_failure_ms")
            category = str(subsystem.get("last_initialize_failure_category", "")).strip()
            message = str(subsystem.get("last_initialize_failure_message", "")).strip()
            entry = f"{name}: failures={count}"
            if isinstance(duration, (int, float)) and duration > 0.0:
                entry += f" last={float(duration):.3f} ms"
            if category:
                entry += f" category={category}"
            if message:
                entry += f" message={message}"
            subsystem_summaries.append(entry)

    if total_failures <= 0 and not subsystem_summaries and not has_last_failure:
        return ""

    lines: List[str] = [f"Total initialization failures: {total_failures}"]
    if isinstance(last_failure, Mapping):
        runtime = str(last_failure.get("runtime", "")).strip()
        subsystem = str(last_failure.get("subsystem", "")).strip()
        category = str(last_failure.get("category", "")).strip()
        message = str(last_failure.get("message", "")).strip()
        duration = last_failure.get("duration_ms")
        details: List[str] = []
        if subsystem:
            details.append(f"subsystem={subsystem}")
        if runtime:
            details.append(f"runtime={runtime}")
        if isinstance(duration, (int, float)) and duration > 0.0:
            details.append(f"duration={float(duration):.3f} ms")
        if category:
            details.append(f"category={category}")
        if details:
            lines.append(f"Last failure: {' '.join(details)}")
        if message:
            lines.append(f"  • Message: {message}")
        lines.append(
            "  • Inspect runtime.lifecycle.initialize_failure logs to correlate with telemetry."
        )

    if subsystem_summaries:
        lines.append("Subsystem failure summary:")
        for summary in subsystem_summaries:
            lines.append(f"  • {summary}")

    lines.append(
        "Consult the runtime diagnostics guide for initialization triage "
        "(docs/modules/runtime/diagnostics.md#initialization-failure-triage)."
    )
    return _format_section("Initialization Failures", lines)


def _format_hot_reload_guidance(diagnostics: Mapping[str, object]) -> str:
    if not isinstance(diagnostics, Mapping):
        return ""

    hot_reload = diagnostics.get("hot_reload")
    lines: List[str] = []

    def _coerce_int(mapping: Mapping[str, object], key: str) -> int:
        value = mapping.get(key)
        if isinstance(value, bool):
            return int(value)
        if isinstance(value, (int, float)):
            return int(value)
        if isinstance(value, str):
            try:
                return int(value)
            except ValueError:
                return 0
        return 0

    if isinstance(hot_reload, Mapping):
        failure_count = _coerce_int(hot_reload, "failure_count")
        cancelled_count = _coerce_int(hot_reload, "cancelled_count")
        rejected_count = _coerce_int(hot_reload, "rejected_count")
        pending_count = _coerce_int(hot_reload, "pending_count")
        loading_count = _coerce_int(hot_reload, "loading_count")
        total_requests = _coerce_int(hot_reload, "total_requests")
        last_error = hot_reload.get("last_error")
        error_hint = hot_reload.get("error_hint")
    else:
        streaming = diagnostics.get("streaming")
        if not isinstance(streaming, Mapping):
            return ""
        failure_count = _coerce_int(streaming, "streaming_total_failed")
        cancelled_count = _coerce_int(streaming, "streaming_total_cancelled")
        rejected_count = _coerce_int(streaming, "streaming_total_rejected")
        pending_count = _coerce_int(streaming, "streaming_pending")
        loading_count = _coerce_int(streaming, "streaming_loading")
        total_requests = _coerce_int(streaming, "streaming_total_requests")
        last_error = None
        error_hint = None

    if all(count <= 0 for count in (failure_count, cancelled_count, rejected_count)):
        return ""

    lines.append(
        "Failed reload attempts: "
        f"{failure_count}" +
        (f" (of {total_requests} observed requests)" if total_requests > 0 else "")
    )

    if failure_count > 0:
        if isinstance(last_error, str) and last_error.strip():
            lines.append(f"  • Last error: {last_error.strip()}")
        if isinstance(error_hint, str) and error_hint.strip():
            lines.append(f"  • Hint: {error_hint.strip()}")
        lines.append("  • Verify the source asset path exists and the watcher has read permissions.")
        lines.append("  • Re-export or regenerate the asset if decoders report stale or corrupt data.")
        if pending_count > 0 or loading_count > 0:
            lines.append(
                "  • Monitor pending/loading handles; excessive backlog can mask repeated reload failures."
            )

    if cancelled_count > 0:
        lines.append(
            "Cancelled reload requests: "
            f"{cancelled_count}. Review cache callbacks to ensure they do not abort reloads prematurely."
        )

    if rejected_count > 0:
        lines.append(
            "Rejected reload requests: "
            f"{rejected_count}. Consider increasing queue capacity or staggering asset edits."
        )

    return _format_section("Hot Reload Guidance", lines)


def _format_stage_timings(diagnostics: Mapping[str, object]) -> str:
    stages = diagnostics.get("stages") if isinstance(diagnostics, Mapping) else None
    if not isinstance(stages, Sequence):
        return ""
    lines: List[str] = []
    for stage in stages:
        if not isinstance(stage, Mapping):
            continue
        name = stage.get("name", "unknown")
        last_ms = stage.get("last_ms")
        average_ms = stage.get("average_ms")
        max_ms = stage.get("max_ms")
        sample_count = stage.get("sample_count")
        if not all(isinstance(value, (int, float)) for value in (last_ms, average_ms, max_ms)):
            continue
        lines.append(
            f"{name}: last={float(last_ms):.4f} ms avg={float(average_ms):.4f} ms "
            f"max={float(max_ms):.4f} ms samples={int(sample_count) if isinstance(sample_count, (int, float)) else 0}"
        )
    return _format_section("Dispatcher Stages", lines)


def _format_subsystems(diagnostics: Mapping[str, object]) -> str:
    subsystems = diagnostics.get("subsystems") if isinstance(diagnostics, Mapping) else None
    if not isinstance(subsystems, Sequence):
        return ""
    lines: List[str] = []
    for subsystem in subsystems:
        if not isinstance(subsystem, Mapping):
            continue
        name = subsystem.get("name", "unknown")
        last_tick_ms = subsystem.get("last_tick_ms")
        max_tick_ms = subsystem.get("max_tick_ms")
        tick_count = subsystem.get("tick_count")
        if not isinstance(last_tick_ms, (int, float)) or not isinstance(max_tick_ms, (int, float)):
            continue
        lines.append(
            f"{name}: last_tick={float(last_tick_ms):.4f} ms max_tick={float(max_tick_ms):.4f} ms "
            f"ticks={int(tick_count) if isinstance(tick_count, (int, float)) else 0}"
        )
    return _format_section("Subsystem Timings", lines)


def _format_scene_validation(diagnostics: Mapping[str, object], max_issues: int) -> str:
    scene = diagnostics.get("scene_validation") if isinstance(diagnostics, Mapping) else None
    if not isinstance(scene, Mapping):
        return ""
    lines = [
        f"Issues: {int(scene.get('issue_count', 0))}",
        f"Cycles: {int(scene.get('cycle_count', 0))}",
        f"Dangling parents: {int(scene.get('dangling_parent_count', 0))}",
        f"Non-finite transforms: {int(scene.get('non_finite_transform_count', 0))}",
    ]
    issues = scene.get("issues")
    if isinstance(issues, Sequence) and issues and max_issues > 0:
        lines.append("Sample issues:")
        for issue in list(issues)[:max_issues]:
            if not isinstance(issue, Mapping):
                continue
            entity = issue.get("entity")
            message = issue.get("message", "")
            related = issue.get("related")
            detail = f"entity={entity}"
            if related is not None:
                detail += f" related={related}"
            if message:
                detail += f" message={message}"
            lines.append(f"  • {detail}")
    return _format_section("Scene Validation", lines)


def _format_metrics(
    diagnostics: Mapping[str, object],
    prefixes: Optional[Sequence[str]],
    *,
    verbose: bool,
) -> str:
    metrics = diagnostics.get("metrics") if isinstance(diagnostics, Mapping) else None
    if not isinstance(metrics, Mapping):
        return ""
    descriptors = metrics.get("descriptors")
    samples = metrics.get("samples")
    if not isinstance(descriptors, Sequence) or not isinstance(samples, Sequence):
        return ""
    prefixes_or_default: Optional[Sequence[str]]
    if prefixes:
        prefixes_or_default = prefixes
    else:
        prefixes_or_default = ("runtime.streaming.",)
    entries = _resolve_metric_entries(descriptors, samples, prefixes_or_default)
    if not entries:
        return ""
    lines = []
    for entry in entries:
        line = (
            f"{entry.name}{entry.formatted_labels()}: {entry.formatted_value()}"
            f"{entry.formatted_unit()}"
        )
        if verbose:
            description = entry.formatted_description()
            if description:
                line += description
        lines.append(line)
    return _format_section("Metrics", lines)


def _select_prefixes(raw_prefixes: Sequence[str]) -> Optional[Sequence[str]]:
    cleaned = [prefix.strip() for prefix in raw_prefixes if prefix and prefix.strip()]
    return tuple(cleaned) if cleaned else None


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    payload = _load_payload(args.input)
    diagnostics = payload.get("runtime_diagnostics")
    if diagnostics is None:
        print("Runtime Telemetry Viewer\n========================")
        print("No runtime diagnostics available in the telemetry payload.")
        return 0
    if not isinstance(diagnostics, Mapping):
        raise SystemExit("error: runtime_diagnostics must be an object")

    prefixes = _select_prefixes(args.metric_prefix)
    sections = [
        _format_frame_summary(payload),
        _format_initialization_failures(diagnostics),
        _format_streaming(diagnostics),
        _format_hot_reload_guidance(diagnostics),
        _format_stage_timings(diagnostics),
        _format_subsystems(diagnostics),
        _format_scene_validation(diagnostics, args.max_issues),
        _format_metrics(diagnostics, prefixes, verbose=args.verbose),
    ]
    header = "Runtime Telemetry Viewer\n========================"
    print(header)
    for section in sections:
        if section:
            print(section)
    return 0


if __name__ == "__main__":
    sys.exit(main())
