from __future__ import annotations

import ctypes
import os
from pathlib import Path
from types import TracebackType
from typing import Dict, Iterable, Iterator, List, Mapping, Optional, Tuple, Type, Union

__all__ = [
    "EngineLibraryNotFound",
    "EngineModuleHandle",
    "EngineRuntimeHandle",
    "load_all_modules",
    "load_module",
    "load_runtime",
]

SearchPath = Union[os.PathLike[str], str]
SearchPaths = Optional[Union[SearchPath, Iterable[SearchPath]]]


class EngineLibraryNotFound(RuntimeError):
    ...


class EngineModuleHandle:
    name: str
    identifier: str
    library: ctypes.CDLL

    def __init__(self, name: str, identifier: str, library: ctypes.CDLL) -> None: ...
    def resolved_name(self) -> str: ...
    def compatibility_metadata(self) -> Mapping[str, object]: ...


class EngineRuntimeHandle:
    library: ctypes.CDLL
    _is_initialized: bool
    _context_owns_runtime: bool
    _supports_average_tick_ms: bool

    def __init__(self, library: ctypes.CDLL) -> None: ...
    def name(self) -> str: ...
    def module_names(self) -> List[str]: ...
    def initialize(self) -> None: ...
    def shutdown(self) -> None: ...
    def tick(self, dt: float) -> None: ...
    def __enter__(self) -> EngineRuntimeHandle: ...
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_value: Optional[BaseException],
        traceback: Optional[TracebackType],
    ) -> None: ...
    def mesh_bounds(self) -> Tuple[Tuple[float, float, float], Tuple[float, float, float]]: ...
    def body_positions(self) -> List[Tuple[float, float, float]]: ...
    def joint_translations(self) -> Dict[str, Tuple[float, float, float]]: ...
    def dispatch_order(self) -> List[str]: ...
    def dispatch_durations(self) -> List[float]: ...
    def average_tick_ms(self) -> Optional[float]: ...
    def scene_nodes(
        self,
    ) -> List[
        Tuple[
            str,
            Tuple[float, float, float],
            Tuple[float, float, float, float],
            Tuple[float, float, float],
        ]
    ]: ...
    def load_modules(self, search_paths: SearchPaths = ...) -> Mapping[str, EngineModuleHandle]: ...


def load_runtime(search_paths: SearchPaths = ...) -> EngineRuntimeHandle: ...

def load_module(module_name: str, search_paths: SearchPaths = ...) -> EngineModuleHandle: ...

def load_all_modules(search_paths: SearchPaths = ...) -> Mapping[str, EngineModuleHandle]: ...


def _canonical_identifier(module_name: str) -> str: ...

def _shared_library_name(identifier: str) -> str: ...

def _load_shared_library(identifier: str, search_paths: SearchPaths) -> ctypes.CDLL: ...

def _candidate_paths(library_name: str, search_paths: SearchPaths) -> Iterator[Path]: ...

def _freeze_search_paths(search_paths: SearchPaths) -> Optional[Tuple[SearchPath, ...]]: ...

def _iter_search_path_bases(search_paths: SearchPaths) -> List[Path]: ...

def _default_search_paths() -> List[Path]: ...
